#sp# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
# Replace with a single Open Collective username
# Replace with a single Ko-fi username
# Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: Pambo Security# Replace with a single Community Bridge project-name e.g., cloud-foundry
# Replace with a single Liberapay username
issuehunt: Keidi# Replace with a single IssueHunt username
otechie: João Loped # Replace with a single Otechie username
lfx_crowdfunding: Pambo Security # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://www.paypal.me/KeidiAO']   # Retom sponsorshi['link1', 'link2']nk2']
